### ISSUE TITLE
Loading module failed when opening a page with charts widget from page with preset URL

### ISSUE THREAD

**Issue by WouterMansystems** [mendixlabs/charts#11]
When opening a page with a charts widget from a page with a preset URL the charts widget won't load.

Reproduction steps:
1) add a URL to your home page
2) navigate from this page to a page with a chart widget

The following error raises in the client console:
GET http://localhost:8080/p/interface/widgets/com/mendix/widget/custom/charts/PlotlyCustom.js?636535054966832099 net::ERR_ABORTED
Error: scriptError
    at l (mxui.js?636535054966832099:7)
    at HTMLScriptElement.<anonymous> (mxui.js?636535054966832099:7)
Loading module failed! Check console log for more detailed debug information.

The GET seems to have a wrong endpoint, the added ...**/p/**... shouldn't be in the request.

**Comment by edwinmp** [comment]
Hi @WouterMansystems, thanks for catching this. It's originating from a path we've been manually setting in the webpack [config](https://github.com/mendixlabs/charts/blob/master/webpack.config.js#L55) that didn't consider the URL setting.
Should be fixed in the next release.

**Comment by brfreek** [comment]
Does this by any means relate to an issue where the widgets are loaded into a phonegap app? We are receiving the following error:
GET file:///android_asset/www/widgets/com/mendix/widget/custom/charts/PlotlyCustom.js?636542135507512030 net::ERR_FILE_NOT_FOUND

I dit not create a new issue regarding this yet. If this is not related to this issue, I will create a new one.

**Comment by Andries-Smit** [comment]
Dear Freek,

The issue, is some how related, the fix for the page URLs is fixed in the next release. We are aware of the phone gap app issue too, we will check if the the page url  fix will also solve the mobile issue.

Cheers,
Andries

**Comment by brfreek** [comment]
Any idea when this will happen (since we have a go-live deadline)

**Comment by Andries-Smit** [comment]
@brfreek The next release will be in beginning next week. Page URL is fixed, tough there is no solution for the mobile at the moment. When is your timeline?

**Comment by brfreek** [comment]
@Andries-Smit We plan to go live at the 23th. I also run into issues cloning the code and compiling it. Is there any way to get in touch to find out how we can resolve this? :)

**Comment by Andries-Smit** [comment]
Issue is resolved in the release 1.0.0-beta 4 
https://appstore.home.mendix.com/link/app/105695/
