### ISSUE TITLE
Sort order Column chart

### ISSUE THREAD

**Issue by roelvanloon** [mendixlabs/charts#12]
Hi,

![neg sortonweeks](https://user-images.githubusercontent.com/22930012/35965625-ca489af0-0cbb-11e8-9d24-7ab824378e37.PNG)
![pos sortonweeks](https://user-images.githubusercontent.com/22930012/35965626-ca623d48-0cbb-11e8-9513-ed3836a04a71.PNG)
ColumnChart sorts correctly based on X axis sort attribute, except in the case where X axis data attribute is negative. In that case first the records with the negative value are shown and then the possitive value. In this case it seems the widget overrules the X axis sort attribute.

Regards,
Roel van Loon

**Comment by edwinmp** [comment]
Hi @roelvanloon, thanks for raising this. Let me look into it and get back to you.

Thanks.

**Comment by Andries-Smit** [comment]
Issue is resolved in version 1.0.0 Beta 4
