### ISSUE TITLE
DateTime Area chart

### ISSUE THREAD

**Issue by TaraCampagne** [mendixlabs/charts#13]
Hi,
When using the area chart the widget doesn't allow to use a dateTime attribute for the x-axes. 
![naamloos](https://user-images.githubusercontent.com/31507613/36072228-4e622100-0f1c-11e8-8837-5c01e3567947.png)

**Comment by edwinmp** [comment]
Hi @TaraCampagne, thanks for raising this. Will have this in with the next release, possibly later this week.

**Comment by Andries-Smit** [comment]
Feature is implemented in version 1.0.0 Beta 4
https://appstore.home.mendix.com/link/app/105695/
