### ISSUE TITLE
Feature request : Save the graphs in an image

### ISSUE THREAD

**Issue by WagleRadhika** [mendixlabs/charts#14]
The widget as is, is extremely useful, however there is no possibility of having this in a PDF.
Request is for saving the created graphs as jpeg/png/jpg image file so that the same graphs can be plugged in PDF.

**Comment by Andries-Smit** [comment]
Radhika,

At the moment, it is not possible. We could look in to enabled the mode bar
https://plot.ly/javascript/configuration-options/#always-display-the-modebar
Is that what you would like to see?

This will enable users to save image from charts in the browser, though it is not possible to create the images on the server to include the in reporting. 

This last feature would be awesome.... but probably out of reach

Cheers, Andries

**Comment by WagleRadhika** [comment]
Hi Andries,

The option to "always-display-the-modebar" is also interesting and will definitely help us in plugging this in our reports. If possible, could you enable this option for the widget, and additionally is it possible to provide a timeline as to when it will be released (as this would help us to communicate the timeline to our users)?

Once again thanks for looking into my requests!

Cheers, 
Radhika

**Comment by Andries-Smit** [comment]
Dear Radhika,

Is this feature is not planned nor place on the road map, there for we can not provide you a timeline. I will discuss the request the product owner. I will keep you posted.

Cheers, Andries

**Comment by WagleRadhika** [comment]
Hi Andries,

Thanks for the update on my query. Looking forward to know the timeline once the feature is planned.
Till then good luck for the final release of the widget, I hope it would be loaded with more features. :)

Cheers,
Radhika

**Comment by Andries-Smit** [comment]
Withing the latest release it is possible to save the image from the mode-bar on the client side 
Tab advanced, Mode `Advanced` Configuration options
``` json
{
  "always-display-the-modebar": true
 }
```
Further documentation can be found here https://plot.ly/javascript/configuration-options/

There will no function created to generate images on the server side.

**Comment by Andries-Smit** [comment]
Generating images server side is available through external services.

https://docs.mendix.com/howto/extensibility/charts-plotly-images-rest
