### ISSUE TITLE
Feature request : Configure series name/ Set the datasets from the database

### ISSUE THREAD

**Issue by WagleRadhika** [mendixlabs/charts#15]
Currently the datasets have to be configured via a microflow/XPath and the series name is hardcoded.
Is it possible to fetch the series name via a microflow? Also the series have to be configured individually, is it possible to enable the option of configuring all the data series (similar to Chartjs). I can imagine that this might be difficult (or maybe impossible) due to the option of configuring layout per data series.

**Comment by Andries-Smit** [comment]
Dear Radhika, 

The requested feature has a high impact. I do not expect it on the roadmap soon. 
Currently we are working towards the final release of the chart widgets. After the final release we will look at this feature.

Cheers, Andries

**Comment by WagleRadhika** [comment]
Thanks for the quick update Andries!

**Comment by binary1230** [comment]
+1, same request here

**Comment by Andries-Smit** [comment]
Released in v1.4.0
