### ISSUE TITLE
As a dev, I would like access to the source code to the sample project

### ISSUE THREAD

**Issue by binary1230** [mendixlabs/charts#17]
Is this mendix app available anywhere to open locally in the modeler?  I see the running app linked but can't figure out from reading the docs if the modeller project is available anywhere

https://charts102.mxapps.io/p/home

**Comment by edwinmp** [comment]
Hi @binary1230... You can find an `mpk` for any of the versions of the test project in the [releases](https://github.com/mendixlabs/charts/releases) section of the repo. Here's the [link](https://github.com/mendixlabs/charts/releases/tag/v1.0.0-Beta3) to the latest release

**Comment by binary1230** [comment]
Oh hey, thanks, that's good info.  Suggestion maybe mention this in the README, or maybe in the demo app itself like 'get MPKs from X location' just so it's more obvious for new Mendix users?
