### ISSUE TITLE
PieChart sort allows sorting on calculated attributes - Error

### ISSUE THREAD

**Issue by NikolausWeiss** [mendixlabs/charts#18]
When using the Pie Chart sort option, the user is allowed to selected calculated attributes. However, when the app is run, the following error appears:  

> An error occurred while retrieving chart data: An error occurred while retrieving data via XPath (//MyModule.calculatedAttribute): An error has occurred while handling the request.

Since all other widgets do not allow sorting on calculated attributes, I assume that is what might be causing the issue.

**Comment by edwinmp** [comment]
Hi @NikolausWeiss, thanks for raising this. Will investigate and get back to you.

**Comment by Andries-Smit** [comment]
Dear Nikolaus.

Unfortunately there is no way to to figure out at the run time, if the attribute is sortable by the database. 
There is no graceful way to catch this error.

For now, you could retrieve the data by microflow you can do you own sorting. Or use the sort attribute in the widget. It will work, as for MF and sort over reference the sorting is done on the client side.

There is an other story in the backlog about optimizing sorting. We might look into the ticket when we will pick that up.

Cheers, 
Andries
