### ISSUE TITLE
Example project of https://charts102.mxapps.io/

### ISSUE THREAD

**Issue by pimvdnoll** [mendixlabs/charts#24]
Hi can the example/test project of https://charts102.mxapps.io/ also on github?

**Comment by djkwagala** [comment]
Dear @pimvdnoll 
The example test project is part of the release as [TestProject.mpk](https://github.com/mendixlabs/charts/releases/download/1.0.0-Beta5/TestProject.mpk)

**Comment by pimvdnoll** [comment]
ow nice! overlooked that one. thnx
