### ISSUE TITLE
De-activating series in stacked area chart does not work

### ISSUE THREAD

**Issue by jeroen-huizer-conclusion** [mendixlabs/charts#25]
When de-activating a series in a stacked are chart, the areas are not 're-stacked' as it were.
The result is that the series that are stacked on the deactivated series are still rendered as if it were active.

Example:
* Series 1: [10 20 30]
* Series 2: [10 20 10]
Show two areas:
* One from [0 0 0] to [10 20 30] 
* One from [10 20 30] to [20 40 40]

When deactivating Series 1 it should render as
* One serie from [0 0 0] to [10 20 10]

Instead it renderes like:
* One serie from [0 0 0] to [20 40 40]

A picture says more than a thousand words, so I included two.

![stacked area chart - all active](https://user-images.githubusercontent.com/21953339/37463139-9611227a-2854-11e8-98b9-50a66822f788.PNG)

![stacked area chart - one active](https://user-images.githubusercontent.com/21953339/37463147-9bcc4b5e-2854-11e8-841c-20bdc04548e0.PNG)

**Comment by Andries-Smit** [comment]
Hi Jeroen,

Thank you for reporting this issue. We will look into this.

Cheers, Andries

**Comment by edwinmp** [comment]
Hi @jeroen-huizer-conclusion, this is fixed now. Please update to the latest version and let me know if the fix is satisfactory.
![adjust-stack-area](https://user-images.githubusercontent.com/5672438/38617642-3c9bf5d8-3da0-11e8-8149-a1fb6273b820.gif)

**Comment by jeroen-huizer-conclusion** [comment]
Thanks guys!
