### ISSUE TITLE
new feature : store generated graph as an image

### ISSUE THREAD

**Issue by snuman** [mendixlabs/charts#27]
Is it possible to store the generated graph as an image object or pass it on to a microflow for further actions. This way you could use the graph in document templates or in emails.

**Comment by Andries-Smit** [comment]
Dear Stephan,

Unfortunately it is not possible to generate the graph server side. It is a feature requested many times before. Though the difficulty that the charts are created by rendering in de browser and can not perform the same action server side. 

I will discuss the request the the product owner but, i don't expect that we could do this with this charting library.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Generating chart images could be done trough external services:

https://docs.mendix.com/howto/extensibility/charts-plotly-images-rest
