### ISSUE TITLE
Give access to configurations options in the "Advanced" tab 

### ISSUE THREAD

**Issue by jumarock** [mendixlabs/charts#30]
For each chart type, it would be great to have access to the plot configuration JSON structure in the "Advanced" tab of the chart settings dialog. This would allow for instance to show the Plotly tool bar which is hidden by default:

![image](https://user-images.githubusercontent.com/14889579/38092536-cea7a0ea-3368-11e8-907e-1ee9974eae0e.png)

**Comment by Andries-Smit** [comment]
Dear jumarock,

Thank you for this feature request. It looks valuable. We will discuss it with the product owner to put it in de backlog.

Cheers,
Andries

**Comment by edwinmp** [comment]
Hi @jumarock,

This feature has been added in version [1.2.0](https://github.com/mendixlabs/charts/releases/tag/v1.2.0)

**Comment by jumarock** [comment]
Hi @edwinmp l,

Many thanks!

**Comment by jumarock** [comment]
Hi @edwinmp ,

I am currently trying to integrate a LineChart (1.2.1) in my Mendix project (7.15.1)
What I do is basically to embed it into a listener data view because the data I want to be displayed in the chart must be changed depending on the selection done in another grid view.
All is working fine until I set some layout and configuration advanced options:
Layout options:
```
{
   "xaxis": {
      "fixedrange": false
   },
   "yaxis": {
      "fixedrange": false
   }
}
```
Configuration options:
```
{
   "displayModeBar": true,
   "displaylogo": false,
   "modeBarButtonsToRemove": ["hoverCompareCartesian"],
   "doubleClick": "reset+autosize"
}
```
The following error is displayed in the web browser:
_An error occurred in a "com.mendix.widget.custom.LineChart.LineChart" widget. Check updates for the widget in the Mendix App Store or contact the widget developer._

To understand a bit more, I tried to use the same chart but with data that are not changed according any selection. The chart works perfectly and the custom options are correctly applied.

Could you give me some clue?

Also, I tried to write a "com.mendix.charts" with those settings into the "theme/widget" directory of my Mendix project. It seems that during the Mendix (7.15.1)project deployment, this directory is not merged into the "deployment\web\widgets" directory which cause the following issue at runtime:
_404 - file not found for file: widgets/com.mendix.charts.json_

Many thanks for your help!

**Comment by edwinmp** [comment]
Hi @jumarock, thanks for raising this. However, I added the layout and configurations options in a LineChart playground and I couldn't replicate the error. If you could provide more detailed steps to replicate, that'd be great. Also check in the console for any errors, that'd be a great help too.

As for the theme file, you're right. I noticed recently that it's not being copied into the deployment directory. Will schedule a fix, perhaps move it into the root theme folder. Please open a separate issue for it.

Regards,
Edwin

**Comment by jumarock** [comment]
Hi @edwinmp ,

I created an issue regarding the com.mendix.charts.json file deployment: #46 
Regarding the Layout & Configuration problem, I will try to create and attache a simple Mendix projet for you to reproduce it.

Best regards,
Julien.

**Comment by jumarock** [comment]
Hi @edwinmp ,

Here is attached a simple Mendix 7.15.1 project (please unzip the attachment).
[Test_LineChart_Contextual-main.zip](https://github.com/mendixlabs/charts/files/2075183/Test_LineChart_Contextual-main.zip)

By selecting a "Chart" object in the left table view, you will see that the Chart cannot be displayed. The following errors are raised:
- In the web browser: 
![image](https://user-images.githubusercontent.com/14889579/41023828-cdda4614-696d-11e8-98ff-636259904752.png)
- In the Mendix console:
![image](https://user-images.githubusercontent.com/14889579/41023867-e2b14a24-696d-11e8-8193-9dd55915a310.png)

If the "Basic" mode is selected in the chart widget, the graph is correctly rendered.

Hope this will help.
Best regards,
Julien.

**Comment by edwinmp** [comment]
Hi @jumarock,

The attachments you shared where very helpful, thank you. Have fixed the issue and plan to have it released in the next few days. In the meantime, you can find a beta version of the widget [here](https://github.com/FlockOfBirds/charts/releases/tag/v1.2.2-beta).

**Comment by jumarock** [comment]
Hi @edwinmp ,

Many thanks, I tried the provided beta version and it works!

Best regards,
Julien.
