### ISSUE TITLE
Sort order Column chart

### ISSUE THREAD

**Issue by roelvanloon** [mendixlabs/charts#35]
See also issue #12.

I have updated the widget with the latest version 1.1.0. Sorting issue with negative values is still existing, in case of using more than 1 series.

See attached file. Bottom chart shows the difference between the 2 series in the upper chart.  For both series I'm using a microflow as data source and sorting within the mf.

Thanks in advance for looking into this issue again.

Regards,
Roel

![knipsel](https://user-images.githubusercontent.com/22930012/38630413-2ab81664-3db7-11e8-8d7f-8c121644049b.PNG)

**Comment by Andries-Smit** [comment]
Dear Roel,

Thanks for reporting this. The behavior is caused by the data type of the x axis combined with gaps in your data set. String x data is sorted by the microflow and added in in the order completion. 

It is recommended to change the data type to dataTime, so the chart will sort automatically.
With `tickformat` the data could be fromated to your liking

```  json{
  xaxis: {
    tickformat: "%m-%Y"
  }
}

**Comment by Andries-Smit** [comment]
Dear Roel,

Replies from email wont show any attachments in Github, so I will guess.

Our widget is based on Plolty, Plotly is based on the d3 lib. The week formatting is only added recently in d3:
https://github.com/d3/d3-time-format/commit/3b8e065cc2ee81dc6bb2bc09f7f972d4a2e676ed

So this option is unfortunately not available in our version. Only when the Plotly maintainers will migrate to the next version it will be available. I dont expect that the happen (soon)

You could try my first suggestion keep string x axis:
> You could add the missing x data to the positive series, and make the bar stacked.

For more information on the ticks see Plolty reference 
https://plot.ly/javascript/reference/#layout-xaxis-tickmode

On x axis time and number plolty will try to show data ticks as good as possible, not show all items.

Cheers, Andries

**Comment by roelvanloon** [comment]
Hi Andries,

Thanks for your help!

I also figured out your solution to make it stacked (1 series instead of 2). But my goal was to show negative values in a different color. That is why I used 2 series.

If I use 1 series with stacked bar, is it possible to color negative values different as positive values? And do you know the JSON format for this? If that is possible then my issue is solved 😊

Thanks,
Roel

Van: Andries Smit [mailto:notifications@github.com]
Verzonden: vrijdag 13 april 2018 11:45
Aan: mendixlabs/charts <charts@noreply.github.com>
CC: Loon, Roel van <Roel.van.Loon@enexis.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [mendixlabs/charts] Sort order Column chart (#35)


Dear Roel,

Replies from email wont show any attachments in Github, so I will guess.

Our widget is based on Plolty, Plotly is based on the d3 lib. The week formatting is only added recently in d3:
d3/d3-time-format@3b8e065<https://github.com/d3/d3-time-format/commit/3b8e065cc2ee81dc6bb2bc09f7f972d4a2e676ed>

So this option is unfortunately not available in our version. Only when the Plotly maintainers will migrate to the next version it will be available. I dont expect that the happen (soon)

You could try my first suggestion keep string x axis:

You could add the missing x data to the positive series, and make the bar stacked.

For more information on the ticks see Plolty reference
https://plot.ly/javascript/reference/#layout-xaxis-tickmode

On x axis time and number plolty will try to show data ticks as good as possible, not show all items.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Don't think you can set a color based on a value like this.
You could use 2 series, one positive one negative, but important to have all weeks available in both series.
Than stack them.

**Comment by Andries-Smit** [comment]
Solved by stacking the value
