### ISSUE TITLE
visible property of series not working

### ISSUE THREAD

**Issue by anthonydickinson** [mendixlabs/charts#37]
Hi,

We have defined a number of series in the area/line chart and would like to initially hide / not show the series. That can be achieved by specifiying on the series a property 'visible' with the value 'legendonly', 
`{"visible": "legendonly"}`

however this is not working. In a codepen for plot.ly / Javascript this is working:

https://codepen.io/anthonydickinson/pen/dmxOJy

Settings:
![visible-settings](https://user-images.githubusercontent.com/4667432/38801091-2ad8f7ac-4169-11e8-9c20-54d84aaeadba.PNG)

Expected result
![visible-expected](https://user-images.githubusercontent.com/4667432/38801089-2aa1061c-4169-11e8-802c-18acac4fec04.PNG)

Actual result:
![visible-result](https://user-images.githubusercontent.com/4667432/38801090-2abe2a08-4169-11e8-84d9-0df8a228ee70.PNG)

**Comment by edwinmp** [comment]
Hi Anthony, thanks for reporting this. You're right, there's a setting in the code that's overwriting this. Will have it fixed in the next release.

**Comment by anthonydickinson** [comment]
Hi great, is there an ETA for this new version perhaps?

**Comment by edwinmp** [comment]
Can get you beta with the fix once it's done, but the official release should be available by Friday next week.

**Comment by anthonydickinson** [comment]
Hi Edwin,

Sure, just let me know when there is a beta.
