### ISSUE TITLE
compare mode of chart not working

### ISSUE THREAD

**Issue by anthonydickinson** [mendixlabs/charts#38]
When hovering a chart, it would be nice to see the same behaviour as in plot.ly is implemented. The hovermode compare is not working as expected, although it seems it is overriding the default settings of the layout.  

`"hovermode":"compare"`

In the codepen this is working: https://codepen.io/anthonydickinson/pen/dmxOJy

**Settings**
![hover-settings](https://user-images.githubusercontent.com/4667432/38801667-c3d9a018-416a-11e8-9762-1f12c56452c6.PNG)

**Expected result or similar**
![hover-expected](https://user-images.githubusercontent.com/4667432/38801664-c39434ce-416a-11e8-8d22-bb34bea46802.png)

**Actual result**
![hover-result](https://user-images.githubusercontent.com/4667432/38801666-c3c1c2cc-416a-11e8-9397-ef216a9857cd.png)

**Comment by edwinmp** [comment]
Hi Anthony, thanks for raising this. This currently removes the default tooltip in favour of the plotly version. If you're fine with this then you'll also need to change the `hoverinfo` setting on each of the series from `none` to one that suits you e.g. `all`, `x+y`, `y`. See the attached GIF.
![hoverinfo](https://user-images.githubusercontent.com/5672438/38803276-61b3e5c6-4177-11e8-8916-506a79f4e2c4.gif)

**Comment by anthonydickinson** [comment]
Hey,

This is what we were looking for. Thx.
