### ISSUE TITLE
AnyChart on click does not work

### ISSUE THREAD

**Issue by mgroeneweg** [mendixlabs/charts#39]
Hi,

I created an AnyChart, displaying the chart works fine but the onclick triggers an error in the console.
Uncaught TypeError: Cannot read property 'eventEntity' of undefined
    at Object.t.onClick (AnyChart.js?636594913359385910:17)
    at n.t.onClick (AnyChart.js?636594913359385910:17)
    at n.emit (chunk5.js:22)
    at HTMLDivElement.t.emit (chunk5.js:55)
    at o (chunk5.js:55)
    at Object.e.exports [as click] (chunk5.js:55)
    at Object.clickFn (chunk5.js:55)
    at HTMLDocument.A (chunk5.js:55)

I created a non-persistent entity with an unlimited string attribute. Client has full access to the entity.
OnClick microflow has the entity as only parameter.

X-axis uses date values, Y-axis uses decimal values.

**Comment by Andries-Smit** [comment]
Hi Marcel 

We have a fix for the issue. We are working on a new feature release (including the fix), planned next week. If you require the fix before we can send you a pre-release, please let me know

Cheers, Andries

**Comment by mgroeneweg** [comment]
Hi Andries,

A pre-release would be great, I can test it in the real customer app. 

With regards,

Marcel

**Comment by edwinmp** [comment]
Hi Marcel, the pre-release with the fix can be found [here](https://github.com/FlockOfBirds/charts/releases/tag/AnyChart-v1.0.2-beta).

**Comment by mgroeneweg** [comment]
Hi Edwin,

Thanks a lot. I will try it with the customer app. Probably not today but definitely soon.

With regards,

Marcel

**Comment by mgroeneweg** [comment]
Hi Edwin,

The onclick event works, but I don't see a reason why the event sends all chart data to the microflow. Just sending the pointNumber, pointIndex, x and y should suffice, to keep the amount of data transferred to the minimum.

With regards,

Marcel

**Comment by edwinmp** [comment]
Hi Marcel, we'd actually stripped away some of the event data, which is the best we can do given the AnyChart's requirement to support every possible chart type. Some charts don't even have x & y values. I'll strip away more of the common bulky properties and return only the point data (for one or more points depending on the `hoverinfo`), whatever it may be. At the moment, I can only see the `data` property as being unnecessary. We're already excluding `fullData`, `xaxis `& `yaxis`.

Regards,

Edwin

**Comment by Andries-Smit** [comment]
Solution is resolved and released in the app store https://appstore.home.mendix.com/link/app/105695/ v1.2.0
