### ISSUE TITLE
AnyChart zooms in when dragging in the chart but user cannot zoom out

### ISSUE THREAD

**Issue by mgroeneweg** [mendixlabs/charts#40]
Hi,

AnyChart zooms in when dragging in the chart but user cannot zoom out. This is hardwired in the widget because the configuration options are fixed: no toolbar and don't allow double click.

(The other charts don't allow zooming.)

This is tied to #30 because allowing that would open the option to configure it.

Until you implement #30, at least make the behavior consistent: either zoom in and out or no zooming at all. Now the user has to reload the page to zoom out.

With regards,

Marcel

**Comment by Andries-Smit** [comment]
Hi Marcel.

The configuration options will be added for the for all chart types in the next release, expected this or next week.

Cheers, Andries

**Comment by Andries-Smit** [comment]
This configurations options has been add in any chart version 1.1.0 and Charts 1.2.0
There zooming could be enabled and disabled, please let me know if this solved your issue
