### ISSUE TITLE
PieChart requires entityContext

### ISSUE THREAD

**Issue by JelleDekker** [mendixlabs/charts#41]
I notice that the PieChart requires entityContext, while it does not seem to do anything with the context object, unless the user would use '[%CurrentObject%]' in the XPath for the dataEntity.

I'd say needsEntityContext can be set to false, now I need to provide one which isn't used at all.

**Comment by Andries-Smit** [comment]
Hi Jelle.

Indeed the context is only need for the constraint or for input of the data source microflow. Not all use cases requires a context. Though to support the context case we have set `needsEntityContext="true"` in the widget xml. So for non context page, you have create a dummy context.

We would love to see an option `needsEntityContext="optional"` but this is not available at the moment.

Cheers,
Andries
