### ISSUE TITLE
Request: support nanoflows

### ISSUE THREAD

**Issue by JelleDekker** [mendixlabs/charts#42]
It would be nice if Charts would support nanoflows as datasource and onClick event.

**Comment by edwinmp** [comment]
Hi Jelle, we've been working on adding nanoflow support to all the widgets and are currently waiting on a Web Modeler update with nanoflow support before releasing this. Will let you know when it's done.

**Comment by Andries-Smit** [comment]
Hi Jelle, 

Don't get too exited, we will add nanoflow support for click events, but not as data source, at the moment.

Cheers, Andries

**Comment by edwinmp** [comment]
Hi Jelle, nanoflow click support has been added in version [1.2.0](https://github.com/mendixlabs/charts/releases/tag/v1.2.0).

Regards, Edwin
