### ISSUE TITLE
com.mendix.charts.json file is not deployed into the "deployment\web\widgets" directory

### ISSUE THREAD

**Issue by jumarock** [mendixlabs/charts#46]
It seems that during the Mendix (7.15.1) project deployment, the "theme/widget" directory containing a "com.mendix.charts.json" file is not merged into the "deployment\web\widgets" directory. 
The following issue at runtime is then encountered:
404 - file not found for file: widgets/com.mendix.charts.json

**Comment by Andries-Smit** [comment]
Dear Jumarock,

Thanks for reporting this issue. It looks like the newer version of the Mendix server is not copying the theme/widget folder any longer to the deployment folder. We will move the the theme configuration to an other directory in the next release.

With kind regards, Andries

**Comment by edwinmp** [comment]
Hi @jumarock ... the widget has been updated to work with a configuration file located directly in the theme folder. You can test with the beta [here](https://github.com/FlockOfBirds/charts/releases/tag/v1.2.2-beta). Will include the fix in the next release.

**Comment by Andries-Smit** [comment]
The fix is release 1.2.2 , now available in the app store.
