### ISSUE TITLE
Request: Export to image (app library)

### ISSUE THREAD

**Issue by sjeefr** [mendixlabs/charts#48]
I would like to export all graph data to PDF and other forms and it would be nice to have the graph in the export as well. This would, presumably, require the image to be available in memory/local app image library, and be set in the document template dynamic image widget.

Can we do that?

For example, ChartJS exports to Base-64, that would be enough :)

**Comment by Andries-Smit** [comment]
Dear Sander.

At the moment it is not possible to save the image grammatically. User can save the image when the toolbar is enabled. see https://github.com/mendixlabs/charts/issues/14

Are you requesting browser side export or a server side export?

Its a much request feature, we will spend some research time on it. Though its hard to accomplish. if you have some suggestions, how we can do this, please let us know. 

Cheers,
Andries

**Comment by Andries-Smit** [comment]
Most viable option is to use plotly.js services (REST)
https://api.plot.ly/v2/images

We research this option and if viable will document for Mendix usage

**Comment by Andries-Smit** [comment]
Dear Sander,

The plotly services REST end point is now added to the documentation.
https://docs.mendix.com/howto/extensibility/charts-plotly-images-rest

Please not that this an external service who will charge  use for usage. Though they have some free tier. 

Cheers, Andries
