### ISSUE TITLE
Multiple Charts - Minified react error

### ISSUE THREAD

**Issue by rkardolus** [mendixlabs/charts#49]
Hi!

When using more than 1 chart widget (and different type of charts) on the same page, a variable number of those widgets show a multipleDefine error. 
The browser console also shows the following error:  “Error: Minified React error #31”

How can this be resolved?

**Comment by Andries-Smit** [comment]
Dear Ralph,

We released a newer version of the chart widget lib, with some major refactoring. We did not work on this issue. But it might be solved too.
Our test project contains many charts on the same page, but we did not see such issues
https://charts102.mxapps.io

Please double check if this issue still occur in the latest version? V1.3.0
https://appstore.home.mendix.com/link/app/105695/

If so we will look further into this.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Closed, no responce
