### ISSUE TITLE
Decimals are rounded in chart

### ISSUE THREAD

**Issue by TolenE** [mendixlabs/charts#5]
I've created a chart using a decimal as y-value. The chart only plots on rounded values.

![chart rounded](https://user-images.githubusercontent.com/9247417/34666461-d230ecf0-f464-11e7-9b4f-5235f0ba6418.png)

**Comment by edwinmp** [comment]
Hi @TolenE, you're right, this is a known issue and will be fixed in the next release. Thanks.

**Comment by Andries-Smit** [comment]
Dear Bart,

This issue is resolved in https://appstore.home.mendix.com/link/app/105695/ 1.0.0-beta3

Cheers,
Andries
