### ISSUE TITLE
Add 'Disbale During Action' setting to microflow events

### ISSUE THREAD

**Issue by t-fitz** [mendixlabs/charts#51]
Hi, 

Can a 'Disable During Action' functionality be added when a microflow is run during the onclick event. 

I've run into errors when someone clicks a chart section more than once and two runs of the microflow come into conflict.

**Comment by Andries-Smit** [comment]
Dear Trevor,

Thank reporting this problem. We will add this feature to the backlog.

Cheers,
Andries

**Comment by Andries-Smit** [comment]
In app store release 1.4.0
