### ISSUE TITLE
Aggregate timestamps

### ISSUE THREAD

**Issue by Narev** [mendixlabs/charts#53]
I was wondering is it possible to aggregate your date from your database directly without having to aggregate server side using a microflow. I found some options for it in the plotly documentation, but those seem to require you to reference the actual x value array. https://plot.ly/javascript/aggregations/

**Comment by djkwagala** [comment]
Dear Pieter van de Braak,
Thank you for the response. This feature is currently being worked upon and will soon be available in the next releases of Charts widget.

Regards
Derrick Kwagala

**Comment by Andries-Smit** [comment]
Hi Pieter,

Current state is in research, we can aggregate with data associated with a x axes objects. Though grouping based on time period (binning) is only supported in Plotly JS with histograms.  

Histograms can be create with Any chart widget
https://appstore.home.mendix.com/link/app/106517/
https://docs.mendix.com/howto/extensibility/charts-any-usage
https://docs.mendix.com/refguide/charts-any-cheat-sheet#statistical-chart
https://plot.ly/javascript/aggregations/#histogram-binning

So there is no concluding on the date nor the functionality.

Cheers,
Andries

**Comment by Andries-Smit** [comment]
Hi Pieter,

We added create a pre-release with aggeregate function in chart. Please have a look, feedback is welcome

https://github.com/FlockOfBirds/charts/releases/download/v1.3.1-beta/Charts.mpk

Please note there is grouping (or binning function)

Cheers, Andries

**Comment by Narev** [comment]
I will definitie have a look tomorrow

**Comment by Andries-Smit** [comment]
Binning feature will not be implemented in charts. Grouping save values is added.
