### ISSUE TITLE
Using dynamic series with microflow as datasources causes an xpath retrieve

### ISSUE THREAD

**Issue by Narev** [mendixlabs/charts#54]
I set up my domain model to be non-persistent, i then set the data source microflow to retrieve my entities. This all seemed fine untill i ran the application. Now it is complaining that it cannot perform the xpath retrieve which seems logical because my series entity is a non-persistant one. While the example is showing you a persistent domain model i think it would be good to specifically mention it in the documentation that you should not use non-persistent entities when you are using dynamic series.

**Comment by Andries-Smit** [comment]
Dear Pieter, 

The dynamic series property is only implemented for the data source `XPath`. For data source Microflow and REST they are not supported at the moment. Unfortunately this is not well document and no appropriate error message is shown when configured differently. 

The dynamic series for REST and Microflow is in our current backlog. We will keep you posted when it will be available.

Cheers, 
Andries

**Comment by Narev** [comment]
Ok, so if there is no way but to persist my series will that also require me to generate my data before hand? Because then i need to persist my graph data which i rather would not do.

**Comment by Andries-Smit** [comment]
Yes, data source XPath is retrieving its data from the database.

**Comment by Narev** [comment]
A quick fix for me would be if you could add an xpath constraint to the series. Because now I'm not able to use my already persisted data as we have a multi tenant environment. So each tennant has his own set of series.

**Comment by djkwagala** [comment]
Good evening @Narev,
We added a possible solution to this issue.
Kindly checkout out the beta release and verify if it satisfies this issue.

https://github.com/mendixlabs/charts/issues/56#issuecomment-419818991

We've added some changes onto Dynamic series. Here's a trial mpk for the [charts widget](https://github.com/FlockOfBirds/charts/releases/download/v1.3.1-beta/Charts.mpk) and the [mendix test project](https://github.com/FlockOfBirds/charts/releases/download/v1.3.1-beta/MxTestProject.mpk). 

Kindly try it out.
https://github.com/FlockOfBirds/charts/releases/tag/v1.3.1-beta

Regards
Derrick Kwagala

**Comment by Andries-Smit** [comment]
Available in the appstore v1.4.0

**Comment by Gielvanaltena** [comment]
I used non-persistant entity for my data sets in my ChartJS widgets. I would like to use dynamic series with a microflow, but using dynamic series with a microflows causes a database retrieve and a error. Please document this. Please supprt this.
