### ISSUE TITLE
Issue with Mendix 7.18.0

### ISSUE THREAD

**Issue by simo101** [mendixlabs/charts#55]
The chart widgets don't seem to render in 7.18.0. This occurred on the line widget and column chart.

**Comment by jseremba** [comment]
Dear @simo101 Thanks for reporting this issue, we'll look into it and get back to you as soon as possible.

**Comment by simo101** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found). 
com.mendix.charts.json?636716511923127962:1 Failed to load resource: the server responded with a status of 404 (Not Found).
![image](https://user-images.githubusercontent.com/1325658/45035335-bf083780-b027-11e8-8262-20dbefaacbd5.png)

**Comment by simo101** [comment]
Example of the setup.
![image](https://user-images.githubusercontent.com/1325658/45035564-45bd1480-b028-11e8-972c-6878ca99e8e9.png)

**Comment by jseremba** [comment]
@simo101 We are currently having trouble to reproduce the issue, kindly provide us with a fresh test project and steps to reproduce.

Cheers
Joseph

**Comment by MarTimeSeries** [comment]
We are having the same issue, but it works fine after we clean our cache. Is there already a solution?

**Comment by djkwagala** [comment]
Dear Simon and MarTimeSeries 
Thanks for alerting us about this issue. We finally reproduced it. We'll add it to the backlog.

Regards
Derrick Kwagala

**Comment by fstockmayer** [comment]
Dear djkwagala,
is there any Update on the current status?
I currently use this Widgets in an IoT-Project and therfore it would be great to know when I can continue the development.

Best Regards,
Florian

**Comment by djkwagala** [comment]
Dear Florian, 
This issue is in the backlog is of high priority. It will be addressed soonest.

**Comment by djkwagala** [comment]
Dear @simo101 @fstockmayer @MarTimeSeries 
We've fixed the bug you were facing. Here's the [fix](https://github.com/FlockOfBirds/charts/releases/download/v1.3.1-beta/Charts.mpk). and [sample test project](https://github.com/FlockOfBirds/charts/releases/download/v1.3.1-beta/ChartsTestProject.mpk)
