### ISSUE TITLE
Unable to compile widget

### ISSUE THREAD

**Issue by rik-bos** [mendixlabs/charts#56]
Hi,

I'd like to do some changes to the widget (for the dynamic series I need an xpath constraint + sorting). Unfortunately I'm not able to compile the widget locally so I cannot test my changes nor put it into my application.

I did a checkout on the project, afterwards an npm install and npm start. I get the output that's in the attachment (error.log).

Could you help me compiling the widget?

Kind regards,
Rik Bos

[error.log](https://github.com/mendixlabs/charts/files/2365499/error.log)

**Comment by djkwagala** [comment]
Good morning Rik Bos,
We've added some changes onto Dynamic series. Here's a trial mpk for the [charts widget](https://github.com/FlockOfBirds/charts/releases/download/v1.3.1-beta/Charts.mpk) and the [mendix test project](https://github.com/FlockOfBirds/charts/releases/download/v1.3.1-beta/MxTestProject.mpk). 

Kindly try it out.
https://github.com/FlockOfBirds/charts/releases/tag/v1.3.1-beta

**Comment by djkwagala** [comment]
Hello Rik,
I've failed to reproduce your error.log, however after reading through your error.log, I deduce the errors are typescript errors. They are arising from the added code changes due to invalid types and typescript caught them.

Regards
Derrick Kwagala

**Comment by rik-bos** [comment]
I was able to compile it now. Thanks for the help!
