### ISSUE TITLE
 add a direct label to the bar chart.

### ISSUE THREAD

**Issue by ChengMaoDSM** [mendixlabs/charts#58]
I wanted to have something like [https://plot.ly/javascript/bar-charts/#bar-chart-with-direct-labels](https://plot.ly/javascript/bar-charts/#bar-chart-with-direct-labels).
I do not see any field that can be used for this number.
![test](https://user-images.githubusercontent.com/43228990/45468618-1176e180-b715-11e8-9f1f-8dc3f8dcf00c.png)

**Comment by Andries-Smit** [comment]
Dear ChengMaoDSM,

At the moment there is no way to move the label inside the bar. The addition json settings could not provided this. It is a feature that need to be build into the chart widget, like we did with the heatmap.

I wil discuss this request with the product owner and will get back to you.

With kind regards, Andries

**Comment by Andries-Smit** [comment]
If the text is show stopper you could consider building the chart from scratch with the Any chart module.  https://appstore.home.mendix.com/link/app/106517/ 
https://docs.mendix.com/refguide/charts-any-configuration

Sample:
https://docs.mendix.com/refguide/charts-any-cheat-sheet#2-6-column-chart
Or use a building block from the module.

Cheers

**Comment by Andries-Smit** [comment]
Will not be implemented in the standard chart widgets, could be solved with any chart
