### ISSUE TITLE
Tooltip form shown twice in case the page parameter is refreshed 

### ISSUE THREAD

**Issue by RianneCLaan** [mendixlabs/charts#60]
Behavior: Tooltip form shown twice in case the page parameter is refreshed 

Situation:
- A line chart with a dynamic series is used.
- Line chart is placed inside a dataview with datasource by microflow that creates new datapoints in case the dropdown field 'day' is changed. 

![tooltip form 1st time](https://user-images.githubusercontent.com/43643250/46147445-d53f9700-c265-11e8-9cd5-aa2fd710a5c3.png)
![tooltip form after refresh](https://user-images.githubusercontent.com/43643250/46147457-d7a1f100-c265-11e8-9694-17c57adab1b1.png)

**Comment by rwburgman** [comment]
We are seeing the same issue (a duplicated tooltip). We are using a bubble chart.

The tooltip seems to work fine if we open the page for the first time, but the tooltip is duplicated if we open a page a second time or refresh the page parameter. Clearing the browser cache solves the issue util the page is opened two times again, of if the page parameter is refreshed again.

![image](https://user-images.githubusercontent.com/2144339/47293605-dbc5f200-d60a-11e8-846a-16e7525329c4.png)

**Comment by rwburgman** [comment]
We are having the same issue. We are using a bubble chart and the tooltip duplicates when we open a page for a second time, or when we refresh a page parameter. Clearing the browser cache solves the issue until the page is opened again or until the parameter is refreshed again.

We are using version 1.4.0 of the widget.

![image](https://user-images.githubusercontent.com/2144339/47294374-2d6f7c00-d60d-11e8-953b-97297ee93df9.png)

**Comment by rwburgman** [comment]
When I move my mouse over a data point I always see 4 new lines in my console: 

`Waarderingen.WaarderingChartTooltip.dataView1: using object 2533274790395905 from context
Waarderingen.WaarderingChartTooltip.dataView1: returning object '2533274790395905'
Waarderingen.WaarderingChartTooltip.dataView1: using object 2533274790395905 from context
Waarderingen.WaarderingChartTooltip.dataView1: returning object '2533274790395905'`

It seems to me that some event is triggered twice or something like that.

**Comment by jseremba** [comment]
Hello @rwburgman @RianneCLaan 
Thank you for raising this issue, we will look in it and get back to you as soon as we can.

Regards
Joseph

**Comment by rwburgman** [comment]
Hi @jseremba 

I did some testing yesterday, and found a work-around. The problem is that the onhover handler is called twice for the same plotly_hover event (after reopening the page). I solved this by adding a boolean on the event when it is processed by the onhover handler, so I can prevent execution of the handler when it is called a second time. But it would be nice if the root cause is solved, so that the event is not processed twice in the first place. Probably something is not correctly uninitialized when the widget is destroyed.

This is the code I used in PlotlyChart.ts around line 120.

`if (onHover) {
	const hoverHandler = function(event: MouseEvent) {
		if ((event as any).plotly_onhover_handled === undefined) {
			(event as any).plotly_onhover_handled = true;
			(onHover as any)(event);
		}
	}
	myPlot.on("plotly_hover", hoverHandler as any);
}`

**Comment by Andries-Smit** [comment]
Beta release is available solving this issue, please let us know if this solves this issue in you projects too https://github.com/FlockOfBirds/charts/releases/tag/v1.4.1-beta

**Comment by rwburgman** [comment]
The beta solved my issue. Thanks.

**Comment by Andries-Smit** [comment]
Version 1.4.1 is now available for download in the app store https://appstore.home.mendix.com/link/app/105695/
