### ISSUE TITLE
file not found for file: com.mendix.charts.json_

### ISSUE THREAD

**Issue by ivosturm** [mendixlabs/charts#65]
When loading any chart out of this widget on the Mendix page this error:

_404 - file not found for file: com.mendix.charts.json_

keeps popping up in the Mendix console. I found in the JS code were it is coming from:

_window.fetch(window.mx.baseUrl+"../com.mendix.charts.json?"+i)_

And indeed this json file is missing in that location...

**Comment by Andries-Smit** [comment]
Hi Ivo, 

This is the global theme file for charts. This should be optional and not influence the working of you app. 
Please let me know if this breaks something.

More information could be found in the documentation https://docs.mendix.com/refguide/charts-configuration#4-chart-theming

I think it should not throw an error in the console. At most a debug message. Ill see if if could taken in in the next sprint.

Cheers, Andries

**Comment by ivosturm** [comment]
Hi Andries,

Thanks for the quick reply! Indeed it does not break anything. It just clogs up the console logging with errors… Any way from our side to make sure this error does not pop up?

Kind regards,
Ivo

Van: Andries Smit <notifications@github.com>
Verzonden: dinsdag 6 november 2018 10:36
Aan: mendixlabs/charts <charts@noreply.github.com>
CC: Ivo Sturm <ivo.sturm@firstconsulting.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [mendixlabs/charts] file not found for file: com.mendix.charts.json_ (#65)


Hi Ivo,

This is the global theme file for charts. This should be optional and not influence the working of you app.
Please let me know if this breaks something.

More information could be found in the documentation https://docs.mendix.com/refguide/charts-configuration#4-chart-theming

I think it should not throw an error in the console. At most a debug message. Ill see if if could taken in in the next sprint.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Hi Ivo, 

Just add the theme file, with an empty object
``` json
{
}
```
Cheers!

**Comment by Andries-Smit** [comment]
We removed the console error in version 1.4.1 which is now available for download in the app store https://appstore.home.mendix.com/link/app/105695/

**Comment by ArthurvdMolen** [comment]
I have the latest version but I get many errors:

404 - file not found for file: com.mendix.charts.json

What is the best way of solving?

**Comment by Jaap01** [comment]
I also get this error in the console running it locally an d I wonder if there is a relation with the error I get using the pie chart. Which is: Maximum call stack size exceeded RangeError: Maximum call stack size exceeded

**Comment by Gielvanaltena** [comment]
I also get the same error in the console. "404 - file not found for file: com.mendix.charts.json". I have tried the Basic, Advanced and Developer options.
