### ISSUE TITLE
Pie Chart ignores sort order setting

### ISSUE THREAD

**Issue by NikolausWeiss** [mendixlabs/charts#7]
When a sort attribute is selected, there is an option underneath, where descending or ascending order can be selected. It seems, however, that this setting is ignored, and that the chart will always sort in ascending order.

Edit: [It looks like the sortOrder is never passed to the properties object here.](https://github.com/mendixlabs/charts/blob/a06654f946b811a3bc5d9be3ff4ab3423e105c6c/src/PieChart/components/PieChartContainer.ts#L74) Therefore it always falls back on the default setting, which is "asc"

**Comment by Andries-Smit** [comment]
Dear Nikolaus,

Thank you for reporting the issue with so much details. We are able to fix it
https://github.com/FlockOfBirds/charts/commit/f7beecff9ebe5f803a6ccf9a7ee28c625dc8a8ef

And it will be in the next release.

Cheers,
Andries

**Comment by Andries-Smit** [comment]
Fix is implemented in version 1.0.0 Beta 4
https://appstore.home.mendix.com/link/app/105695/
