### ISSUE TITLE
Incorrect loading of charts i.c.w. listen-to widgets and template grids

### ISSUE THREAD

**Issue by Maarten-Nelissen** [mendixlabs/charts#70]
When using charts i.c.w. listen-to widgets or template grids data is loaded incorrectly.

When clicking another item in the listen-to list or when navigating to a second page in a template grid charts regularly show data from a previous graph that was on the same location in the UI.

I expect this to be caused by the fact that the charts store is global for all charts in the session, charts data is never removed from the store within a session and that the mendix chart widget is re-used with different context when you change listen-to item or navigate to next page in a template grid.

Besides that there is also a piece of code that causes an infinite loop when there are +20 charts with the same friendlyId (which is easily possible when using a chart in a listview or template grid or when navigating to the same page with different context) due to this global store:

.\src\utils\data.ts L497

export const generateInstanceID = (friendlyId: string) => `${friendlyId}-${Math.round(Math.random() * 20)}`;
export const getInstanceID = (friendlyId: string, store: Store, reduxStoreKey: ReduxStoreKey): string => {
    let instanceID = generateInstanceID(friendlyId);
    const instances: string[] = Object.keys(store.getState()[reduxStoreKey]);
    while (instances.indexOf(instanceID) > -1) {
        instanceID = generateInstanceID(friendlyId);
    }

    return instanceID;
};

**Comment by Andries-Smit** [comment]
Hi Maarten, we are working on the limitation and will release soon.
Though would not think a page with a charts would perform well.

**Comment by Maarten-Nelissen** [comment]
Thanks!
We have a maximum of 6 charts per page, and this performs well.
If we have more charts we place them on a new page.

**Comment by Maarten-Nelissen** [comment]
I see there is a new release (1.4.1) with a fix for the issue with more than 20 charts.

"Removed the limit that no more than 20 charts can be placed on a single page (Ticket #76997, GitHub issue #70)" - Not yet tested it because we already fixed the issue locally.

I just want to add that it is not just within a single page. Due to the fact that the Redux store is global and charts that are uninitialized are not removed from the store you get to this 20 really quickly when you navigate through multiple pages with charts with the same friendly ID. 

Also this causes performance issues with an ever increasing cache and conflicts between charts with the same friendly ID in lists and template grids.

Is the above also fixed by the 1.4.1 release?

**Comment by djkwagala** [comment]
Hi Maarten,
This was fixed in 1.4.1 release of charts widget.

Regards
Derrick Kwagala

**Comment by Maarten-Nelissen** [comment]
Great, thanks Derrick!

**Comment by Andries-Smit** [comment]
Version 1.4.1 is available for download in the app store https://appstore.home.mendix.com/link/app/105695/
