### ISSUE TITLE
After building the widget the CSS contains javascript

### ISSUE THREAD

**Issue by BartReyserhove** [mendixlabs/charts#77]
I wanted to upgrade the plotly.js dependency towards 1.45.0 or higher because from that version on plotly.js supports circular dependencies for the sankey chart.

I changed the dependency and then I ran npm run build. Everything is build but when using the widget in my app it acted very strange.

I investigated the issue and apparently the anychart.css contains a lot of javascript. 

After removing the javascript from the CSS everything worked fine but I do not know what caused the javascript to be added to the CSS. I see there were some recent changes to the build process. Maybe they are causing it?

Btw, would be great if the next offical version upgrade the plotly.js dependency to something above 1.45.00 ;-)

**Comment by Andries-Smit** [comment]
Thanks Bart. We planning to do an minor update of chart in the coming
weeks. We will add the newer version of the charts to

**Comment by BartReyserhove** [comment]
Ok. I will keep an eye on it then.

**Comment by Andries-Smit** [comment]
We update the lib to Plotly JS library to 1.47.4
And is available in Chart 1.4.2 and Any Chart 1.2.0
