### ISSUE TITLE
Sort ordering ignored for column chart with microflow source

### ISSUE THREAD

**Issue by WouterMansystems** [mendixlabs/charts#8]
The sort attribute is an integer but the columns are not sorted. The data source used is a microflow

**Comment by edwinmp** [comment]
Hi @WouterMansystems, this is the expected behaviour. The sort attribute only applies when the data source is database. When data is from a microflow, sorting is expected to be done within the microflow.

**Comment by WouterMansystems** [comment]
Like everywhere in Mendix, true. Maybe helpful to add to the description of the 'X axis sort attribute':  Only applicable for data source Database. Can otherwise be confusing.

**Comment by edwinmp** [comment]
There is a description on each of the charts.
![image](https://user-images.githubusercontent.com/5672438/35734868-a14ee99c-0833-11e8-92f1-9903144bc499.png)

**Comment by WouterMansystems** [comment]
Not in the current version:
![image](https://user-images.githubusercontent.com/36075182/35735087-af5637e4-0823-11e8-852e-0026bd5bc914.png)

But thanks
