### ISSUE TITLE
Error t.get is not a function when used in the latest Mendix Pro 8 modeler

### ISSUE THREAD

**Issue by sushumab-tammina** [mendixlabs/charts#81]
Hi,
We are facing the following error when upgraded our project to Mendix Pro 8. The Charts widget is throwing an error like t.get is not a function.
![image](https://user-images.githubusercontent.com/21303976/58630963-a13dd980-82fe-11e9-8a6e-ac0a10460db2.png)

**Comment by Andries-Smit** [comment]
For data source MF is an known issue this will be fixed in Beta 2, which will be released soon. Please let us know when this does not work for you. Cheers.

**Comment by Andries-Smit** [comment]
Mendix 8 Beta 2 is available and solves this issue.
