### ISSUE TITLE
The on click event Show a page opens a full page while the page is a pop-up

### ISSUE THREAD

**Issue by WouterMansystems** [mendixlabs/charts#9]
The problem occured with a column chart. The 'On click page' was a page with a pup-up layout. The page opens full page and not as a pop-up.

**Comment by edwinmp** [comment]
Hi @WouterMansystems, thanks for raising this. It's a Mendix issue I'm hoping will be rectified in a future version. One alternative (not ideal) is to add a property that lets the user explicitly choose how they wish to open the form. Will schedule a fix in a future release.

Thanks.

**Comment by Andries-Smit** [comment]
Hi Wouter, 

The issue can not be solved due to the lack of information at runtime. We will no fix it. Though we add nano flow support so you can op a page with a nano flow, which wil take in account the layout settings.

Cheers. Andries

**Comment by edwinmp** [comment]
Hi Wouter,

We've added a feature for specifying the page location in version [1.2.0](https://github.com/mendixlabs/charts/releases/tag/v1.2.0). Now you can choose how you want your page opened.

Regards, Edwin.
